services:
  torproxy:
    image: shinomineko/torproxy:latest
    container_name: torproxy
    networks:
      - darklight

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: darklight:latest
    container_name: scheduler
    environment:
      - CONFIG_FILE=config.ini
    volumes:
      - ./config.ini:/usr/src/app/config.ini:ro
    networks:
      - darklight
      - database

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: darklight:latest
    container_name: worker
    command: ["celery", "worker", "-A", "crawler.tasks", "--autoscale=1,7"]
    environment:
      - CONFIG_FILE=config.ini
    volumes:
      - ./config.ini:/usr/src/app/config.ini:ro
      - ./pipeline/source:/usr/src/app/pipeline/source:ro
      - ./extract.py:/usr/src/app/extract.py:ro
      - ./screenshot:/usr/src/app/screenshot
    networks:
      - darklight
      - database

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - darklight

networks:
  darklight:
    name: darklight
  database:
    name: database
    external: true
